
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path("./assets")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1500x1000")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 1000,
    width = 1500,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_text(
    630.0,
    114.0,
    anchor="nw",
    text="Add new student",
    fill="#000000",
    font=("Inter Medium", 36 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("addStudent.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=620.0,
    y=515.0,
    width=260.0,
    height=50.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("goBack.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=109.0,
    y=89.0,
    width=125.0,
    height=50.0
)

canvas.create_text(
    109.0,
    287.0,
    anchor="nw",
    text="Student 1",
    fill="#000000",
    font=("Roboto", 28 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    721.0,
    301.0,
    image=entry_image_1
)
entry_1 = Text(
    bd=0,
    bg="#FFFFFF",
    highlightthickness=1
)
entry_1.place(
    x=276.0,
    y=276.0,
    width=890.0,
    height=48.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("dropDown.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=1192.0,
    y=276.0,
    width=200.0,
    height=50.0
)

canvas.create_text(
    1270.0,
    294.0,
    anchor="nw",
    text="class",
    fill="#000000",
    font=("Inter Medium", 18 * -1)
)

canvas.create_text(
    108.0,
    384.0,
    anchor="nw",
    text="Student 2",
    fill="#000000",
    font=("Roboto", 28 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    720.0,
    398.0,
    image=entry_image_2
)
entry_2 = Text(
    bd=0,
    bg="#FFFFFF",
    highlightthickness=1
)
entry_2.place(
    x=275.0,
    y=373.0,
    width=890.0,
    height=48.0
)

button_image_4 = PhotoImage(
    file=relative_to_assets("dropDown.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=1191.0,
    y=373.0,
    width=200.0,
    height=50.0
)

canvas.create_text(
    1270.0,
    391.0,
    anchor="nw",
    text="class",
    fill="#000000",
    font=("Inter Medium", 18 * -1)
)
window.resizable(False, False)
window.mainloop()
