# Generated by Django 4.0.3 on 2022-03-20 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExcelFunctions',
        ),
        migrations.DeleteModel(
            name='MathFunctions',
        ),
    ]
